language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g npm-cli-login
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh $NPM_USERNAME $NPM_PASSWORD $NPM_EMAIL